grades_app/config/routes.rb
Rails.application.routes.draw do
  
devise_for :users 
devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    resources :schedules
end



root "schedules#index"
end

grades_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

grades_app/app/models/schedule.rb
class Schedule < ApplicationRecord
    belongs_to :user

    attr_accessor :total_points

    def total_points
    end

    
end

grades_app/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :schedules


  
end

grades_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

grades_app/app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :authenticate_user!, only: [:index, :create, :update, :destroy, :new]
  before_action :set_schedule, only: %i[ show edit update destroy]
  before_action :set_user
  def index
    @schedules = @user.schedules.all
  end
  
  def show
  end


  def new
    @schedule = @user.schedules.new
  end

  def create
    @schedule = @user.schedules.new(schedule_params)
    respond_to do |format|
      if @schedule.save
        format.html { redirect_to schedule_url(@schedule), notice: "Schedule was successfully created." }
        format.json {render :show, status: :created, location: @schedule }
      else
        format.html {render :new, status: :unprocessable_entity}
        format.json { render json: @schedule.errors, status: :unprocessable_entity}
      end
    end
  end




  private
  def set_user
    @user = current_user
  end

  def schedule_params
    params.require(:schedule).permit(:title)
  end

  def set_schedule
    @schedule = Schedule.find(params[:id])
  end


end

grades_app/app/helpers/application_helper.rb
module ApplicationHelper
end

grades_app/app/helpers/schedules_helper.rb
module SchedulesHelper
end

grades_app/app/helpers/student_class_helper.rb
module StudentClassHelper
end

grades_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GradesApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <nav class="navbar navbar-light bg-dark">
    <a class="navbar-brand text-light" href="/">Canyon's Portfolio</a>
    <form class="form-inline">
    <% if user_signed_in? %>
    <div class="text-nowrap text-light" style="padding-right: 10px;">
      Logged in as <strong><%= current_user.email %></strong>
    </div>
      <%= link_to 'Edit profile', edit_user_registration_path, class: "btn btn-success" %> 
      <div style="padding-left: 10px;">
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-primary" %>
      </div>
  
  
    <% else %>
      <%= link_to "Login", new_user_session_path, class: "btn btn-success" %>
      <div style="padding-left: 10px;">
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary" %>
      </div>
    <% end %>
    </form>
  </nav>

    <%= yield %>
  </body>
</html>

grades_app/app/views/schedules/_form.html.erb
<%= form_with(model: schedule, local: true) do |form| %>
    <% if schedule.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>
  
        <ul>
        <% schedule.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  <body class= "text-center bg-light">
    <div class="field">
      <%= form.label :title %>
      <br>
      <%= form.text_field :title %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  </body>
  <% end %>

grades_app/app/views/schedules/index.html.erb
<h1>Schedules#index</h1>
<div class="container">
    <!-- Example row of columns -->
    <div class="row">
        <% @schedules.each do |schedule| %>
            <div class="col-md-4 text-truncate">
                <%= link_to schedule.title, schedule_path(schedule)%>
            </div>
        <% end %>
    </div>

</div> <!-- /container -->

<div class="New Schedule d-flex justify-content-center">
    <%= link_to 'New Schedule', new_schedule_path, class: "btn btn-primary btn-sm"%>
  </div>

grades_app/app/views/schedules/new.html.erb
<h1 class= "bg-info p-5 mg-2">New Schedule</h1>

<%= render 'form', schedule: @schedule %>
<%= link_to 'Back', schedules_path %>

grades_app/app/views/schedules/show.html.erb
<h1><%= @schedule.title %></h1>
<p><%= @schedule.total_points %></h1>